send_notification:
  name: PagerDuty Notification
  description: Send a notification to PagerDuty Service ID.
  fields:
    service_id:
      description: The ID of the PagerDuty service.
      example: "your_service_id"
