name: Hassfest

on:
  push:
    paths:
      - 'custom_components/**'
  pull_request:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
        - uses: "actions/checkout@v3"
        - uses: "home-assistant/actions/hassfest@master"

