name: Purge Old Beta

on:
  pull_request:
  workflow_dispatch:

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
            keep_latest: 10
            keep_min_download_counts: 1
            delete_expired_data: 1
            delete_prerelease_only: True
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}