name: Validate

on:
  push:
    paths:
      - 'custom_components/**'
  pull_request:
  workflow_dispatch:  

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"